module.exports = {
  engineType: ['Gasoline', 'Diesel', 'Hybrid', 'Electric'],
  carsModels: {
    AC:["Cobra", "378 GT Zagato"],
    Acura: ["MDX","NSX","RL","RDX","CSX","ZDX", "TLX"],
    AlfaRomeo:["TLX", "Giulia", "Giulietta", "GT", "Spider", "Brera", "MiTo", "Disco Volante", "Stelvio"],
    AstonMartin:["DB9", "V12 Vanquish", "V8 Vantage", "Virage", "DBS", "Rapide", "Cygnet", "DB11"],
    Audi:["A3", "A4", "A5", "A6", "A8", "RS4", "RS6", "S3", "S4", "S6", "S8", "TT", "Q7", "R8", "Q5", "RS5", "A1", "A7", "RS3", "Q3", "SQ5", "S1", "TTS"],
    Bentley: ["Arnage", "Azure", "Brooklands", "Continental Flying Spur", "Mulsanne", "Flying Spur", "Continental GT", "Bentayga"],
    BMW: ["Serie 1", "Serie 2", "Serie 3", "Serie 5","Serie 7","X1","X3", "X5", "X6", "Z4", "i3", "i8", "1M", "M2", "M3", "M5", "M6","X2 Concept"],
    Bristol: ["Blenheim", "Fighter", "Blenheim Speedster"],
    Bugatti: [ "EB Veyron 16.4", "Chiron"],
    Cadillac: ["CTS", "Escalade", "XLR", "SRX", "BLS", "STS", "DTS", "ATS", "XT5"],
    Chevrolet: ["Astra", "Camaro", "Caprice", "Corvette", "Impala", "Malibu", "Niva", "Suburban", "Tahoe", "Tracker", "TrailBlazer", "Zafira", "Equinox", "Spark", "Colorado"],
    Citroen: ["Berlingo", "C1", "C2", "C3", "C3 Picasso", "C4", "C4 Picasso", "C5", "C6", "Xsara Picasso", "Jumpy", "DS3", "DS4","DS5", "C4 Aircross", "C4 Cactus", "C-ZERO", "Nemo", "C-Quatre" ],
    Dacia:["Logan", "Sandero", "Duster", "Lodgy", "Dokker", ],
    Dodge:["Avenger", "Caravan", "Dakota", "Durango", "RAM", "Caliber", "Magnum", "Viper", "Nitro"],
    Ferrari:["612", "599", "F430", "California", "FF", "F12berlinetta", "LaFerrari", "488", "GTC4Lusso", "Portofino", "Testarosa", "Enzo"],
    Fiat: ["500", "500XL", "Bravo", "Sedan", "Croma", "Fiorino", "Multipla", "Panda", "Punto", "Seicento", "Siena", "Strada", "Tipo", "Ulysse", "Idea", "Scudo", "Linea", "Freemont"],
    Seat: ["Altea", "Ibiza", "Toledo", "Leon"],
    Ford: ["Focus", "Fiesta", "Kuga", "Escape", "Expedition", "Explorer", "Galaxy", "Crown Victoria", "Econoline", "Mustang", "Freestyle", "GT", "Ranger", "ourneo Connect", "Edge", "Everest", "Fusion", "EcoSport" ],
    GMC: ["Envoy", "Savana", "Yukon", "Sierra", "Acadia", "Terrain", "Canyon"],
    Honda: ["Accord", "Avancier", "City", "Civic", "CR-V", "Fit", "Insight", "Inspire", "Jazz", "Legend", "Life", "Mobilio", "Pilot", "S2000", "Stepwgn", "Stream", "Fit Aria", "NSX", "Ridgeline", "Elysion", "Grace", "Brio"],
    Hummer:["H2", "H3"],
    Hyundai:["Accent", "Atos", "Centennial", "Getz", "Elantra", "Matrix", "Sonata", "Tucson", "Coupe", "Verna", "Grandeur", "Genesis", "i20", "i30", "Kona", "Click"],
    Infiniti:["FX", "EX", "M", "G", "QX56", "JX", "QX70", "Q50", "QX50", "Q60", "QX60"],
    Jaguar:["S-Type", "X-Type", "XJ", "XK", "XF", "XE", "XFR", "XKR", "XJR"],
    Kia:["Carens", "Carnival", "Magentis", "Opirus", "Pride", "Rio", "Sorento", "Sportage", "Spectra", "Forte"],
    Lamborghini:["Murcielago", "Gallardo", "Reventon", "Aventador", "Huracán", "Veneno", "Sesto Elemento", "Centanario", "Egoista"],
    Maybach:["57", "62"],
    Mazda:["MX-5", "Atenza", "Carol", "Demio", "Premacy", "RX-8", "Spiano", "5", "6", "Bongo", "Verisa", "Flair Crossover", "CX-8"],
    McLaren:["P1", "650S", "675LT", "570S", "540C", "570GT", "720S"],
    MercedesBenz: ["A-klasse", "C-klasse", "CL-klasse", "E-klasse", "G-klasse", "M-klasse", "s-klasse", "SLR McLaren", "Vito", "AMG GT", "AMG GLE"],
    Opel:["Meriva", "Signum", "Tigra", "Astra", "Zafira", "Vectra", "Corsa", "Antara", "Insignia", "Mokka", "Vivaro"],
    Peugeot:["206", "207", "208", "307", "308", "405", "607", "807", "1007", "Partner", "Expert", "4007", "3008", "5008", "RCZ", "208 GTi", "308 GTi", "Montana"],
    Renault: ["Clio", "Kadjar", "Megane", "Laguna", "Scenic", "Kangoo", "Espacio", "Safrane", "Twingo", "Koleos", "Captur", "Lodgy", "Dokker", "Talisman", "Alaskan"],
    RollsRoyce:["Ghost", "Phantom", "Wraith", "Dawn"],
    Saab:["9-3", "9-5", "9-7X", "9-4X"],
    Subaru:["Forester", "Impreza", "Justy", "Legacy", "Pleo"]
  }
}